name: Node Binary Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Protoc (needed based on dependencies)
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Install cargo-risczero (referenced from Makefile)
      - name: Install cargo-risczero
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-risczero@1.0.5

      # Install risc0-zkvm toolchain (based on Makefile)
      - name: Install risc0-zkvm toolchain
        run: make install-risczero

      # Build node binary with mock_da feature (default)
      - name: Build node with mock_da
        run: |
          cd crates/rollup
          cargo build --bin node

    #   # Build node binary with celestia_da feature
    #   - name: Build node with celestia_da
    #     run: cargo build --bin node --no-default-features --features celestia_da

      # Run tests
      - name: Run tests
        run: cargo test
